---
    - name: Create config dir for systemd-resolved
      file:
        path: /etc/systemd/resolved.conf.d/
        state: directory
        mode: '0777'
        owner: systemd-resolve
        group: systemd-resolve
    - name: Create config file for systemd-resolved
      copy:
        dest: /etc/systemd/resolved.conf.d/consul.conf
        mode: '0664'
        owner: systemd-resolve
        group: systemd-resolve
        content: |
          [Resolve]
          DNS=127.0.0.1
          DNSSEC=false
          Domains=~consul
    - name: Redirect local DNS - PPREROUTING udp
      iptables:
        table: nat
        chain: PREROUTING
        protocol: udp
        match: udp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
    - name: Redirect local DNS - PREROUTING tcp
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        match: tcp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
    - name: Redirect local DNS - OUTPUT udp
      iptables:
        table: nat
        chain: OUTPUT
        protocol: udp
        match: udp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
        destination: localhost
    - name: Redirect local DNS - OUTPUT tcp
      iptables:
        table: nat
        chain: OUTPUT
        protocol: tcp
        match: tcp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
        destination: localhost
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
        daemon_reload: true
...