---
- name: Bootstrap Vault
  hosts:
    - vault_instances
  become: true
  gather_facts: true
  any_errors_fatal: true
  roles:
    - role: ansible-vault
      vars:
        vault_version: 1.14.2
  tasks:
    - name: init Vault
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/vault.yaml"

- name: Bootstrap consul servers & agents
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  pre_tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - jq
          - python3-pip
          - python3-netaddr
          - unzip
        state: present
      delegate_to: 127.0.0.1
      run_once: true
  roles:
    - role: ansible-consul
      vars:
        consul_cloud_autodiscovery: false
        consul_tls_enable: true
        consul_version: "1.15.2"
    - role: geerlingguy.docker

  tasks:
    - name: init Consul
      ansible.builtin.include_tasks:
        file: "{{ playbook_dir }}/consul.yaml"

- name: Bootstrap nomad servers & agents
  hosts: nomad_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - role: ansible-nomad
      vars:
        nomad_docker_enable: true
        nomad_raft_protocol: 3
        nomad_telemetry: true
        nomad_telemetry_prometheus_metrics: true
        nomad_telemetry_publish_allocation_metrics: true
        nomad_telemetry_publish_node_metrics: true
        nomad_use_consul: true
        nomad_version: "1.5.6"
...
