---
- name: Bootstrap consul servers & agents
  hosts: consul_instances
  any_errors_fatal: true
  become: true
  become_user: root
  pre_tasks:
    - name: Install packages
      apt:
        update_cache: yes
        pkg:
          - python3-pip
          - python3-netaddr
          - unzip
        state: present
      delegate_to: 127.0.0.1
      run_once: true
  roles:
    - role: ansible-consul
      vars:
        consul_cloud_autodiscovery: false
        consul_version: "1.15.2"
    - role: geerlingguy.docker

  tasks:
    - name: Create config dir for systemd-resolved
      file:
        path: /etc/systemd/resolved.conf.d/
        state: directory
        mode: '0777'
        owner: systemd-resolve
        group: systemd-resolve
    - name: Create config file for systemd-resolved
      copy:
        dest: /etc/systemd/resolved.conf.d/consul.conf
        mode: '0664'
        owner: systemd-resolve
        group: systemd-resolve
        content: |
          [Resolve]
          DNS=127.0.0.1
          DNSSEC=false
          Domains=~consul
    - name: Redirect local DNS - PPREROUTING udp
      iptables:
        table: nat
        chain: PREROUTING
        protocol: udp
        match: udp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
    - name: Redirect local DNS - PREROUTING tcp
      iptables:
        table: nat
        chain: PREROUTING
        protocol: tcp
        match: tcp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
    - name: Redirect local DNS - OUTPUT udp
      iptables:
        table: nat
        chain: OUTPUT
        protocol: udp
        match: udp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
        destination: localhost
    - name: Redirect local DNS - OUTPUT tcp
      iptables:
        table: nat
        chain: OUTPUT
        protocol: tcp
        match: tcp
        destination_port: 53
        jump: REDIRECT
        to_ports: 8600
        destination: localhost
    - name: Restart systemd-resolved
      systemd:
        name: systemd-resolved
        state: restarted
        daemon_reload: true

- name: Bootstrap nomad servers & agents
  hosts: nomad_instances
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - role: ansible-nomad
      vars:
        nomad_docker_enable: true
        nomad_raft_protocol: 3
        nomad_telemetry: true
        nomad_telemetry_prometheus_metrics: true
        nomad_telemetry_publish_allocation_metrics: true
        nomad_telemetry_publish_node_metrics: true
        nomad_use_consul: true
        nomad_version: "1.5.6"
...
